import { auth } from '../lib/firebase';

// Client-side Gemini service calling secure server-side API endpoint
export async function getAIResponse(userMessage: string): Promise<string> {
  if (!userMessage.trim()) {
    return "Please enter a valid query for DRAGO AI.";
  }

  try {
    let token = "";
    if (auth.currentUser) {
      token = await auth.currentUser.getIdToken();
    }

    const res = await fetch("/api/gemini", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${token}`
      },
      body: JSON.stringify({ prompt: userMessage }),
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      return errData.error || `AI Service error (status ${res.status})`;
    }

    const data = await res.json();
    return data.response || "No response generated by AI model.";
  } catch (error: any) {
    console.error("Gemini client proxy error:", error);
    return `Error connecting to AI service: ${error?.message || 'Network error'}`;
  }
}
