import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, CheckCircle2, Home as HomeIcon, Loader2, MapPin, Search, ShieldCheck, UserRound, Wrench } from 'lucide-react';
import { AppScreen, Worker } from '../types';
import { PUNCHX_50_CATEGORIES } from '../data/categories';
import { getCatalogCategory } from '../data/serviceCatalogs';
import ServiceCategoryModal from './ServiceCategoryModal';
import PUNCHX_LOGO from '../assets/logo';
import { getAccurateCurrentPosition, reverseGeocodeCoords } from '../lib/location';

interface Props { onTransition:(target:AppScreen)=>void; onSelectWorker:(worker:Worker)=>void; onSelectCategory:(category:string)=>void; citizenName:string; citizenAddress:string; onOpenProfile?:()=>void; }
const POPULAR=['Electrician','Plumber','Carpenter','AC Technician','Cleaner/Housekeeper','Painter'];

export default function CitizenHomeCatalog({onTransition,onSelectCategory,citizenName,citizenAddress,onOpenProfile}:Props){
  const [query,setQuery]=useState(''); const [area,setArea]=useState('Choose your location'); const [areaAddress,setAreaAddress]=useState(''); const [residential,setResidential]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
  const [catalogOpen,setCatalogOpen]=useState(false);
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return PUNCHX_50_CATEGORIES.filter(c=>!q||`${c.name} ${c.shortDesc} ${c.keywords.join(' ')}`.toLowerCase().includes(q));},[query]);
  useEffect(()=>{try{setResidential(localStorage.getItem('punchx_residential_address_label')||citizenAddress||'');}catch{}},[citizenAddress]);
  useEffect(()=>{let cancelled=false;const refresh=async()=>{if(!navigator.geolocation){setMessage('Location is not supported on this device.');return;}setLoading(true);setMessage('Updating service area…');try{const p=await getAccurateCurrentPosition(true);const r=await reverseGeocodeCoords(p.lat,p.lng);if(cancelled)return;const next=r.area||r.city||'Local Area';setArea(next);setAreaAddress(r.address||'');localStorage.setItem('punchx_user_location',JSON.stringify({lat:p.lat,lng:p.lng,area:next,address:r.address,city:r.city,sector:r.sector,timestamp:new Date().toISOString()}));setMessage('Service area updated');}catch{if(!cancelled)setMessage('Choose your service location to continue.');}finally{if(!cancelled)setLoading(false);}};refresh();const onVisible=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',onVisible);return()=>{cancelled=true;document.removeEventListener('visibilitychange',onVisible);};},[]);
  const goToCategory=(name?:string)=>{setQuery('');setCatalogOpen(true);};
  const handleCatalogSelect=(category:string)=>{onSelectCategory(category);setCatalogOpen(false);onTransition('providers');};
  return <div className="min-h-screen bg-[#f7f7f8] pb-20 text-[#17191d]">
    <header className="sticky top-0 z-40 border-b border-black/5 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-6xl items-center gap-3 px-4 py-2 sm:px-6"><img src={PUNCHX_LOGO} alt="PUNCHX" className="h-9 w-9 rounded-xl object-contain"/><span className="text-xl font-black">PUNCHX</span><button onClick={()=>onTransition('customer-setup')} className="ml-1 flex min-w-0 max-w-[55%] items-center gap-2 rounded-xl px-2 py-2 text-left hover:bg-[#f6f7f9]"><MapPin className="h-4 w-4 shrink-0 text-[#7358d7]"/><span className="min-w-0"><span className="block text-[10px] font-bold uppercase tracking-wider text-[#8b9098]">Service area</span><span className="block truncate text-xs font-black">{area}</span></span>{loading&&<Loader2 className="h-4 w-4 animate-spin text-[#7358d7]"/>}</button><button onClick={onOpenProfile} className="ml-auto flex h-10 items-center gap-2 rounded-xl bg-[#f4f5f7] px-3"><UserRound className="h-4 w-4"/><span className="hidden max-w-28 truncate text-xs font-bold sm:block">{citizenName||'Profile'}</span></button></div><div className="mx-auto flex max-w-6xl items-center gap-2 border-t border-black/5 px-4 py-2 sm:px-6"><MapPin className="h-3.5 w-3.5 text-[#7358d7]"/><span className="truncate text-[11px] font-semibold text-[#70757e]">{areaAddress||'Current device area is used for geofencing.'}</span><span className="ml-auto text-[10px] font-bold text-[#7358d7]">{message}</span></div></header>
    <main className="mx-auto max-w-6xl px-4 sm:px-6"><section className="pt-5"><div className="rounded-[28px] bg-[#17191d] p-5 text-white sm:p-8"><div className="flex items-center gap-2 text-xs font-bold text-white/70"><ShieldCheck className="h-4 w-4 text-[#b9a4ff]"/> Verified local professionals</div><h1 className="mt-3 text-3xl font-black sm:text-5xl">What service do you need today?</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">Tap search to browse every PUNCHX service. Then choose the main service, the service group, and the exact work before PUNCHX checks professional availability.</p><button type="button" onClick={()=>goToCategory()} className="mt-5 flex w-full items-center gap-2 rounded-2xl bg-white p-2 text-left shadow-sm"><Search className="ml-2 h-5 w-5 text-[#777c85]"/><span className="flex-1 px-1 py-3 text-sm font-semibold text-[#777c85]">Search for a service...</span><span className="rounded-xl bg-[#7358d7] px-4 py-3 text-xs font-black text-white">Search</span></button></div></section>
      <section className="pt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#858a93]"><HomeIcon className="h-4 w-4 text-[#7358d7]"/> Residential address</div><div className="mt-2 text-sm font-black">{residential||'Not added yet'}</div><div className="mt-1 text-[10px] text-[#777c85]">Professional visit destination. This does not update the device geofence.</div></div><div className="rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#858a93]"><CalendarDays className="h-4 w-4 text-[#7358d7]"/> Booking flow</div><div className="mt-2 text-sm font-black">Main service → service group → exact work → availability → booking</div><div className="mt-1 text-[10px] text-[#777c85]">Availability is checked only after the exact service is selected.</div></div></section>
      <section className="pt-7"><div className="flex items-end justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-[#7358d7]">Popular</div><h2 className="mt-1 text-2xl font-black">Popular services</h2></div><button onClick={()=>goToCategory()} className="text-sm font-extrabold text-[#7358d7]">See all 50</button></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{POPULAR.map(name=><button key={name} onClick={()=>goToCategory(name)} className="rounded-2xl border border-black/5 bg-white p-4 text-left shadow-sm hover:-translate-y-0.5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f0ecff]"><Wrench className="h-5 w-5 text-[#7358d7]"/></div><div className="mt-4 text-sm font-black">{name}</div><div className="mt-1 text-[10px] text-[#858a93]">Choose exact work</div></button>)}</div></section>
      <section className="py-8"><div className="flex items-end justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-[#7358d7]">Complete catalogue</div><h2 className="mt-1 text-2xl font-black">All 50 services</h2></div><button onClick={()=>goToCategory()} className="text-xs font-bold text-[#7358d7]">Open catalogue</button></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{matches.map(cat=>{const c=getCatalogCategory(cat.id);return <button key={cat.id} onClick={()=>goToCategory(cat.name)} className="overflow-hidden rounded-2xl border border-black/5 bg-white text-left shadow-sm hover:ring-2 hover:ring-[#7358d7]/20"><img src={c?.image} alt="" className="h-28 w-full object-cover bg-[#f1f2f4]" loading="lazy"/><div className="p-3"><div className="text-sm font-black">{cat.name}</div><div className="mt-1 line-clamp-2 text-[10px] leading-4 text-[#777c85]">{cat.shortDesc}</div><div className="mt-2 flex items-center justify-between text-[10px] font-extrabold text-[#7358d7]"><span>Choose services</span><ArrowRight className="h-3.5 w-3.5"/></div></div></button>})}</div></section>
      <section className="pb-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><ShieldCheck className="h-5 w-5 text-[#7358d7]"/><h3 className="mt-3 font-black">Verified professionals</h3><p className="mt-1 text-xs text-[#777c85]">Only approved records can enter matching.</p></div><div className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><CalendarDays className="h-5 w-5 text-[#7358d7]"/><h3 className="mt-3 font-black">Availability after exact work</h3><p className="mt-1 text-xs text-[#777c85]">The unavailable message is not shown before the final service choice.</p></div><div className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><CheckCircle2 className="h-5 w-5 text-[#7358d7]"/><h3 className="mt-3 font-black">Residential visit</h3><p className="mt-1 text-xs text-[#777c85]">The confirmed address is sent to the professional.</p></div></section>
    </main>
    <ServiceCategoryModal isOpen={catalogOpen} onClose={()=>setCatalogOpen(false)} mode="citizen" onSelectCategory={handleCatalogSelect} titleOverride="Choose a service" />
  </div>;
}
