import React, { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot } from 'firebase/firestore';
import { ArrowLeft, CalendarDays, Check, ChevronRight, Home, MapPin, Search, Share2, ShieldCheck, Star, UserRound, X } from 'lucide-react';
import { db } from '../lib/firebase';
import { AppScreen, Worker } from '../types';
import { PUNCHX_50_CATEGORIES, isCategoryMatching } from '../data/categories';
import { getCatalogCategory, ServiceCategory, ServicesSubcategory, ServiceItem } from '../data/serviceCatalogs';
import { DEMO_PROFESSIONALS } from '../data/demoProfessionals';
import { isServiceAreaMatch } from '../lib/location';

interface Props { onTransition:(target:AppScreen)=>void; selectedCategory:string; onSelectCategory?:(category:string)=>void; onSelectWorker:(worker:Worker)=>void; showNotification:(msg:string)=>void; citizenAddress:string; setCitizenAddress:(address:string)=>void; }
type Step='categories'|'subcategories'|'services'|'providers'|'booking';
type ResidentialAddress={house:string;street:string;landmark:string;villageArea:string;city:string;district:string;state:string;pinCode:string};
const EMPTY:ResidentialAddress={house:'',street:'',landmark:'',villageArea:'',city:'',district:'',state:'',pinCode:''};
const DEMO_ENABLED=import.meta.env.DEV||import.meta.env.VITE_ENABLE_DEMO_PROFESSIONALS==='true';
const norm=(v?:string)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const addressLabel=(a:ResidentialAddress)=>[a.house,a.street,a.landmark,a.villageArea,a.city,a.district,a.state,a.pinCode].filter(Boolean).join(', ');
const loadAddress=()=>{try{return {...EMPTY,...JSON.parse(localStorage.getItem('punchx_residential_address')||'{}')};}catch{return EMPTY;}};
const readGeo=()=>{try{const v=JSON.parse(localStorage.getItem('punchx_user_location')||'null');return v&&typeof v.lat==='number'&&typeof v.lng==='number'?v:null;}catch{return null;}};

export default function CitizenServiceCatalogFlow({onTransition,selectedCategory,onSelectCategory,onSelectWorker,showNotification,citizenAddress,setCitizenAddress}:Props){
 const initial=getCatalogCategory(selectedCategory||'');
 const [step,setStep]=useState<Step>(initial?'subcategories':'categories'); const [category,setCategory]=useState<ServiceCategory|null>(initial||null); const [subcategory,setSubcategory]=useState<ServicesSubcategory|null>(null); const [service,setService]=useState<ServiceItem|null>(null); const [workers,setWorkers]=useState<Worker[]>([]); const [matching,setMatching]=useState<Worker[]>([]); const [search,setSearch]=useState(''); const [expanded,setExpanded]=useState<string|null>(null); const [available,setAvailable]=useState(false); const [availabilityMessage,setAvailabilityMessage]=useState(''); const [address,setAddress]=useState<ResidentialAddress>(loadAddress); const [date,setDate]=useState(''); const [time,setTime]=useState(''); const [geo,setGeo]=useState(readGeo()); const [saving,setSaving]=useState(false);
 useEffect(()=>{const refresh=()=>setGeo(readGeo());refresh();window.addEventListener('storage',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('storage',refresh);document.removeEventListener('visibilitychange',refresh);};},[]);
 useEffect(()=>{const unsub=onSnapshot(collection(db,'workerApplications'),snap=>{const approved=snap.docs.filter(d=>String(d.data().status||'').toUpperCase()==='APPROVED').map(d=>{const x=d.data();const loc=x.location&&typeof x.location.lat==='number'&&typeof x.location.lng==='number'?x.location:typeof x.lat==='number'&&typeof x.lng==='number'?{lat:x.lat,lng:x.lng}:undefined;return {id:d.id,name:String(x.legalName||'Verified Professional'),category:String(x.skill||x.category||'Professional'),categories:Array.isArray(x.categories)?x.categories.map(String):undefined,rating:Number(x.rating||0),reviewsCount:Number(x.reviewsCount||0),avatar:String(x.photoURL||x.avatar||''),proBadge:'AUTHORIZED',price:Number(x.visitingFee||x.price||0),visitingFee:Number(x.visitingFee||0),available:x.available!==false,phone:String(x.phone||''),address:String(x.address||''),area:String(x.area||''),sector:String(x.sector||''),serviceAreas:Array.isArray(x.serviceAreas)?x.serviceAreas.map(String):Array.isArray(x.geofenceAreas)?x.geofenceAreas.map(String):undefined,geofenceAreas:Array.isArray(x.geofenceAreas)?x.geofenceAreas.map(String):undefined,location:loc,completedJobs:Number(x.completedJobs||0),jobsCompletedCount:Number(x.completedJobs||0)} as Worker;});setWorkers(DEMO_ENABLED?[...DEMO_PROFESSIONALS,...approved]:approved);},()=>setWorkers(DEMO_ENABLED?DEMO_PROFESSIONALS:[]));return()=>unsub();},[]);
 const categories=useMemo(()=>{const q=norm(search);return q?PUNCHX_50_CATEGORIES.filter(c=>norm(`${c.name} ${c.shortDesc} ${c.keywords.join(' ')}`).includes(q)):PUNCHX_50_CATEGORIES;},[search]);
 const subs=useMemo(()=>{if(!category)return[];const q=norm(search);return q?category.subcategories.filter(s=>norm(`${s.name} ${s.description} ${s.items.map(i=>i.name).join(' ')}`).includes(q)):category.subcategories;},[category,search]);
 const services=useMemo(()=>{if(!subcategory)return[];const q=norm(search);return q?subcategory.items.filter(i=>norm(`${i.name} ${i.description}`).includes(q)):subcategory.items;},[subcategory,search]);
 const checkAvailability=()=>{
  if(!category||!service)return false;
  if(!geo){setAvailable(false);setMatching([]);setAvailabilityMessage('Allow location access to check service availability in your area.');return false;}
  const customerAreaLabels=[geo.area,geo.sector,geo.city,geo.address].filter(Boolean).map(String); const found=workers.filter(w=>{if(w.available===false)return false;const cat=isCategoryMatching(w.categories||w.category,category.name)||isCategoryMatching(w.categories||w.category,category.id);if(!cat)return false;const workerAreas=(w as any).serviceAreas||(w as any).geofenceAreas||[w.area,w.sector].filter(Boolean);return isServiceAreaMatch(customerAreaLabels,workerAreas);});
  setMatching(found);setAvailable(found.length>0);setAvailabilityMessage(found.length?`${found.length} verified professional${found.length===1?'':'s'} available`:'Service is not available on your area.');return found.length>0;
 };
 const chooseCategory=(c:ServiceCategory)=>{setCategory(c);setSubcategory(null);setService(null);setSearch('');setStep('subcategories');onSelectCategory?.(c.name);};
 const chooseSub=(s:ServicesSubcategory)=>{setSubcategory(s);setService(null);setSearch('');setStep('services');};
 const chooseService=(s:ServiceItem)=>{setService(s);setAvailable(false);setMatching([]);setAvailabilityMessage('');};
 const continueService=()=>{if(checkAvailability())setStep('providers');};
 const chooseWorker=(w:Worker)=>{onSelectWorker(w);setStep('booking');};
 const back=()=>{if(step==='categories')onTransition('home');else if(step==='subcategories'){setStep('categories');setCategory(null);}else if(step==='services'){setStep('subcategories');setSubcategory(null);setService(null);}else if(step==='providers'){setStep('services');setMatching([]);setAvailable(false);}else setStep('providers');setSearch('');};
 const continueBooking=()=>{if(!service||!category||!date||!time){showNotification('Please choose a date and time.');return;}const required=['house','street','villageArea','city','district','state','pinCode'] as const;if(required.some(k=>!address[k].trim())){showNotification('Please complete the residential address, including landmark, village/area, city, district, state and PIN.');return;}const formatted=addressLabel(address);setSaving(true);try{localStorage.setItem('punchx_residential_address',JSON.stringify(address));localStorage.setItem('punchx_residential_address_label',formatted);localStorage.setItem('punchx_pending_booking',JSON.stringify({serviceId:service.id,serviceName:service.name,category:category.name,subcategory:subcategory?.name||'',description:service.description,price:service.price,address:formatted,residentialAddress:address,date,time,dispatchMode:'AUTO_MATCH',serviceAvailabilityChecked:true,serviceAvailable:true,geofenceArea:geo?.area||'',geofenceCity:geo?.city||'',geofenceType:'named-area',geofenceAreasChecked:true,workerId:matching[0]?.id||null,workerName:matching[0]?.name||null,createdAt:new Date().toISOString()}));setCitizenAddress(formatted);onSelectCategory?.(category.name);onTransition('payment');}finally{setSaving(false);}};
 const header=<header className="sticky top-0 z-40 border-b border-black/5 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center gap-2 px-3 py-2 sm:px-6"><button onClick={back} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-black/10 bg-white"><ArrowLeft className="h-5 w-5"/></button><div className="min-w-0 flex-1"><div className="truncate text-lg font-black">{category?.name||'PUNCHX Services'}</div><div className="flex items-center gap-1 text-[10px] text-[#777c85]"><MapPin className="h-3 w-3"/>{geo?.area||'Service area not detected'} · named service areas</div></div><button className="flex h-10 w-10 items-center justify-center rounded-full border border-black/10 bg-white"><Search className="h-5 w-5"/></button><button className="hidden h-10 w-10 items-center justify-center rounded-full border border-black/10 bg-white sm:flex"><Share2 className="h-4 w-4"/></button></div></header>;
 return <div className="min-h-screen bg-[#f7f7f8] pb-24 text-[#17191d]">{header}<main className="mx-auto max-w-5xl px-3 py-3 sm:px-6 sm:py-5"><div className="mb-3 flex items-center gap-2 rounded-xl border border-black/5 bg-white px-3 py-2.5"><Search className="h-4 w-4 text-[#777c85]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={step==='categories'?'Search all 50 services':`Search ${category?.name||'services'}`} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none"/>{search&&<button onClick={()=>setSearch('')}><X className="h-4 w-4 text-[#777c85]"/></button>}</div>
 {step==='categories'&&<><div className="mb-4 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="text-[10px] font-bold uppercase tracking-wider text-[#7358d7]">PUNCHX Home Services</div><h1 className="mt-1 text-2xl font-black">All 50 services</h1><p className="mt-1 text-xs text-[#777c85]">Main service → facility → exact work → availability.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{categories.map(cat=>{const c=getCatalogCategory(cat.id);return <button key={cat.id} onClick={()=>c&&chooseCategory(c)} className="overflow-hidden rounded-2xl border border-black/5 bg-white p-2 text-left shadow-sm hover:ring-2 hover:ring-[#7358d7]/20"><img src={c?.image} alt="" className="h-24 w-full rounded-xl object-cover bg-[#f1f2f4]"/><div className="px-1 pt-2 text-sm font-black">{cat.name}</div><div className="px-1 pt-1 line-clamp-2 text-[10px] leading-4 text-[#777c85]">{cat.shortDesc}</div></button>})}</div></>}
 {step==='subcategories'&&category&&<><div className="mb-3 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="text-[10px] font-bold uppercase tracking-wider text-[#858992]">{category.name}</div><h1 className="mt-1 text-2xl font-black">Choose a service type</h1><p className="mt-1 text-xs text-[#777c85]">Select the facility such as fan, bulb, doorbell, switch & socket and more.</p></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{subs.map(s=><button key={s.id} onClick={()=>chooseSub(s)} className="flex gap-3 rounded-2xl border border-black/5 bg-white p-3 text-left shadow-sm"><img src={s.image} alt="" className="h-20 w-20 shrink-0 rounded-xl object-cover bg-[#f1f2f4]"/><div className="min-w-0"><div className="font-black">{s.name}</div><div className="mt-1 text-[11px] leading-4 text-[#777c85]">{s.description}</div><div className="mt-2 text-[10px] font-black text-[#7358d7]">{s.items.length} exact services <ChevronRight className="inline h-3 w-3"/></div></div></button>)}</div></>}
 {step==='services'&&category&&subcategory&&<><div className="mb-2 flex items-center gap-1 text-xs text-[#777c85]"><span>{category.name}</span><ChevronRight className="h-3 w-3"/><span className="font-black text-[#17191d]">{subcategory.name}</span></div><div className="mb-3 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black">{category.name}</h1></div><div className="rounded-xl bg-emerald-50 px-3 py-2 text-right"><div className="text-[9px] font-black text-emerald-700">EARLIEST</div><div className="text-xs font-black">Wed, 8:00 AM</div></div></div><div className="mt-3 flex items-center gap-2 rounded-xl border border-black/5 bg-[#fbfbfc] p-3"><ShieldCheck className="h-5 w-5 text-[#15945a]"/><div><div className="text-xs font-black">Get visitation fee off</div><div className="text-[10px] text-[#777c85]">On eligible orders above ₹499</div></div></div></div><div className="border-t border-black/5 pt-3"><h2 className="mb-2 text-lg font-black">{subcategory.name}</h2>{services.map(item=><article key={item.id} className="border-b border-black/10 bg-white py-4 first:rounded-t-2xl last:rounded-b-2xl"><div className="flex gap-3 px-3 sm:px-4"><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><h3 className="text-base font-black leading-5">{item.name}</h3>{item.popular&&<span className="rounded-full bg-[#f0ecff] px-2 py-1 text-[9px] font-black text-[#7358d7]">Popular</span>}</div><div className="mt-1 text-xs font-black">₹{item.price.toLocaleString('en-IN')}</div><div className="mt-1 text-[10px] text-[#777c85]">{item.duration}</div>{expanded===item.id&&<p className="mt-2 text-[11px] leading-5 text-[#555a63]">{item.description}</p>}<div className="mt-3 flex items-center gap-3"><button onClick={()=>chooseService(item)} className={`rounded-lg px-5 py-2 text-xs font-black ${service?.id===item.id?'bg-[#7358d7] text-white':'border border-[#7358d7] bg-white text-[#7358d7]'}`}>{service?.id===item.id?'Selected':'Add'}</button><button onClick={()=>setExpanded(expanded===item.id?null:item.id)} className="text-xs font-bold text-[#7358d7]">{expanded===item.id?'Hide details':'View details'}</button></div></div></div></article>)}</div>{service&&<div className="sticky bottom-3 z-30 mt-3 rounded-2xl bg-white p-3 shadow-2xl ring-1 ring-black/10"><div className="flex items-center justify-between"><div><div className="text-[10px] text-[#777c85]">Selected service</div><div className="text-sm font-black">{service.name}</div></div><div className="text-sm font-black">₹{service.price.toLocaleString('en-IN')}</div></div><button onClick={continueService} className="mt-3 w-full rounded-xl bg-[#7358d7] py-3 text-sm font-black text-white">Check availability & continue</button></div>}</>}
 {step==='providers'&&service&&<><div className="mb-3 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="text-[10px] font-bold uppercase tracking-wider text-[#7358d7]">Available professionals</div><h1 className="mt-1 text-2xl font-black">{service.name}</h1><p className="mt-1 text-xs text-[#777c85]">{availabilityMessage}</p></div>{matching.length?<div className="space-y-3">{matching.map(w=><button key={w.id} onClick={()=>chooseWorker(w)} className="flex w-full items-center gap-3 rounded-2xl border border-black/5 bg-white p-4 text-left shadow-sm hover:ring-2 hover:ring-[#7358d7]/20"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-full bg-[#f0ecff]">{w.avatar?<img src={w.avatar} alt="" className="h-full w-full object-cover"/>:<UserRound className="h-6 w-6 text-[#7358d7]"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><div className="truncate text-sm font-black">{w.name}</div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-black text-emerald-700">VERIFIED</span></div><div className="mt-1 flex items-center gap-2 text-[11px] text-[#666b74]"><Star className="h-3 w-3 fill-current"/>{w.rating.toFixed(1)} · {w.reviewsCount} reviews · {w.completedJobs||0} jobs</div><div className="mt-1 text-[10px] text-[#777c85]">{w.area||w.sector||'Within your service area'}</div></div><ChevronRight className="h-5 w-5 text-[#7358d7]"/></button>)}</div>:<div className="rounded-2xl border border-red-100 bg-red-50 p-5 text-center"><div className="text-base font-black text-red-700">Service is not available on your area.</div><p className="mt-1 text-xs text-red-600">No approved professional matched this exact booking request.</p></div>}</>}
 {step==='booking'&&service&&category&&<><div className="mb-3 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="text-[10px] font-bold uppercase tracking-wider text-[#7358d7]">Booking</div><h1 className="mt-1 text-xl font-black">{service.name}</h1><p className="mt-1 text-xs text-[#777c85]">Professional selected. Now choose date, time and the residential visit address.</p></div><section className="rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="flex items-center gap-2 text-sm font-black"><CalendarDays className="h-5 w-5 text-[#7358d7]"/>1. Select date & time</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} min={new Date().toISOString().slice(0,10)} className="rounded-xl border border-black/10 px-3 py-3 text-sm font-semibold outline-none"/><select value={time} onChange={e=>setTime(e.target.value)} className="rounded-xl border border-black/10 px-3 py-3 text-sm font-semibold outline-none"><option value="">Select time slot</option><option>8:00 AM – 9:00 AM</option><option>10:00 AM – 11:00 AM</option><option>12:00 PM – 1:00 PM</option><option>2:00 PM – 3:00 PM</option><option>4:00 PM – 5:00 PM</option><option>6:00 PM – 7:00 PM</option></select></div></section><section className="mt-3 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="flex items-center gap-2 text-sm font-black"><Home className="h-5 w-5 text-[#7358d7]"/>2. Residential address</div><p className="mt-1 text-[10px] leading-4 text-[#777c85]">This is the place the professional will visit. It is not used as the device geofence.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{([['house','House / Flat / Building'],['street','Street / Road'],['landmark','Landmark'],['villageArea','Village / Area'],['city','City'],['district','District'],['state','State'],['pinCode','PIN code']] as const).map(([key,label])=><input key={key} value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})} placeholder={label} className="rounded-xl border border-black/10 px-3 py-3 text-sm outline-none focus:border-[#7358d7]"/>)}</div></section><div className="mt-3 rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="text-sm font-black">3. Review</div><div className="mt-2 text-xs text-[#555a63]">{service.name} · ₹{service.price.toLocaleString('en-IN')} · {date||'Date not selected'} · {time||'Time not selected'}</div><div className="mt-1 text-[10px] text-[#777c85]">Visit: {addressLabel(address)||'Residential address not complete'}</div></div><button disabled={saving} onClick={continueBooking} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#7358d7] py-4 text-sm font-black text-white disabled:opacity-50">Continue to payment <ChevronRight className="h-4 w-4"/></button></>}
 </main></div>;
}
