import React, { useEffect, useMemo, useState } from 'react';
import { collection, getDocs, onSnapshot, query, where } from 'firebase/firestore';
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, MapPin, Search, ShieldCheck, UserRound, UsersRound, Wrench, X } from 'lucide-react';
import { auth, db } from '../lib/firebase';
import { AppScreen, Worker } from '../types';
import { PUNCHX_50_CATEGORIES, isCategoryMatching } from '../data/categories';
import { DEMO_PROFESSIONALS } from '../data/demoProfessionals';
import { PUNCHX_COMMERCE, formatINR } from '../config/punchxCommerce';
import { calculateDistanceKm } from '../lib/location';

type Service = {
  id: string; name: string; category: string; subcategory: string; description: string;
  price?: number; duration?: string; reviews?: number; rating?: number; image?: string; faqs?: string[]; demo?: boolean;
};

interface Props {
  onTransition: (target: AppScreen) => void; selectedCategory: string; onSelectCategory?: (category: string) => void;
  onSelectWorker: (worker: Worker) => void; showNotification: (message: string) => void;
  citizenAddress: string; setCitizenAddress?: (address: string) => void;
}

const DEMO_PROFESSIONALS_ENABLED = import.meta.env.DEV || import.meta.env.VITE_ENABLE_DEMO_PROFESSIONALS === 'true';

const normalize = (id: string, data: any): Service | null => {
  const name = String(data.name || data.title || '').trim(); const category = String(data.category || data.serviceCategory || '').trim();
  if (!name || !category) return null;
  const rawPrice = data.price ?? data.startingPrice ?? data.basePrice; const price = Number(rawPrice);
  return { id, name, category, subcategory: String(data.subcategory || data.serviceGroup || data.group || 'Services'),
    description: String(data.description || data.shortDescription || 'Service details are provided by PUNCHX.'),
    price: Number.isFinite(price) ? price : undefined, duration: typeof data.duration === 'string' ? data.duration : undefined,
    reviews: typeof data.reviewsCount === 'number' ? data.reviewsCount : undefined, rating: typeof data.rating === 'number' ? data.rating : undefined,
    image: typeof data.image === 'string' ? data.image : undefined, faqs: Array.isArray(data.faqs) ? data.faqs.map(String) : undefined, demo: false };
};

const DEMO_SERVICES: Service[] = PUNCHX_50_CATEGORIES.map(item => ({ id: `demo-service-${item.id}`, name: `${item.name} Test Service`, category: item.name,
  subcategory: 'Demo service for QA testing', description: `Temporary PUNCHX demo service for testing the ${item.name} booking flow. This service is not a real customer offering.`,
  price: Number(item.basePrice || 199), duration: '60 min', reviews: 0, rating: 0, demo: true }));

export default function SimpleProvidersFlow({ onTransition, selectedCategory, onSelectCategory, onSelectWorker, showNotification, citizenAddress, setCitizenAddress }: Props) {
  const [services, setServices] = useState<Service[]>([]); const [workers, setWorkers] = useState<Worker[]>([]); const [loading, setLoading] = useState(true);
  const [step, setStep] = useState<'services'|'details'|'location'|'datetime'|'summary'>('services'); const [queryText, setQueryText] = useState('');
  const [selected, setSelected] = useState<Service | null>(null); const [selectedWorker, setSelectedWorker] = useState<Worker | null>(null);
  const [dispatchMode, setDispatchMode] = useState<'AUTO_MATCH'|'PERSONAL_SELECT'>('AUTO_MATCH'); const [bookingTiming, setBookingTiming] = useState<'instant'|'later'>('instant'); const [completedWithSelectedWorker, setCompletedWithSelectedWorker] = useState(0); const [countLoading, setCountLoading] = useState(false);
  const [address, setAddress] = useState(citizenAddress || ''); const [date, setDate] = useState(''); const [time, setTime] = useState('');
  const [customerGeo] = useState<{lat:number;lng:number;area?:string;city?:string}|null>(() => { try { const v=JSON.parse(localStorage.getItem('punchx_user_location')||'null'); return v&&typeof v.lat==='number'&&typeof v.lng==='number'?v:null; } catch { return null; } });
  useEffect(() => setAddress(citizenAddress || ''), [citizenAddress]);

  useEffect(() => { const unsub = onSnapshot(collection(db, 'services'), snapshot => { const next = snapshot.docs.map(doc => normalize(doc.id, doc.data())).filter(Boolean) as Service[]; setServices(next.filter(s => (s as any).active !== false)); setLoading(false); }, error => { console.warn('PUNCHX service catalogue:', error); setServices([]); setLoading(false); }); return () => unsub(); }, []);
  useEffect(() => {
    const unsub = onSnapshot(collection(db, 'workerApplications'), async snapshot => {
      try {
        const userSnap = await getDocs(query(collection(db, 'users'), where('role', '==', 'worker')));
        const onlineByUid = new Map(userSnap.docs.map(d => [d.id, d.data()?.workerAvailability === true || d.data()?.isOnline === true]));
        const next: Worker[] = snapshot.docs.filter(doc => doc.data().status === 'APPROVED').map(doc => {
          const data = doc.data();
          const uid = String(data.uid || doc.id);
          return { id: doc.id, uid, name: String(data.legalName || 'Verified Professional'), category: String(data.skill || data.category || 'Professional'), categories: Array.isArray(data.categories) ? data.categories : undefined, rating: typeof data.rating === 'number' ? data.rating : 0, reviewsCount: typeof data.reviewsCount === 'number' ? data.reviewsCount : 0, avatar: String(data.photoURL || data.avatar || ''), proBadge: 'AUTHORIZED', price: Number(data.visitingFee || data.price || 0), visitingFee: Number(data.visitingFee || 0), available: data.available !== false, isOnline: onlineByUid.get(uid) === true, phone: String(data.phone || ''), address: String(data.address || ''), area: String(data.area || ''), sector: String(data.sector || ''), location: data.location && typeof data.location.lat === 'number' && typeof data.location.lng === 'number' ? {lat:Number(data.location.lat),lng:Number(data.location.lng)} : undefined, completedJobs: Number(data.completedJobs || data.workerCompletedJobs || 0), jobsCompletedCount: Number(data.completedJobs || data.workerCompletedJobs || 0), onTimeRate: data.onTimeRate ? String(data.onTimeRate) : undefined, identityVerified: data.identityVerified === true, skillVerified: data.skillVerified === true, backgroundChecked: data.backgroundChecked === true, trainingCertified: data.trainingCertified === true, insuranceCovered: data.insuranceCovered === true } as Worker;
        });
        setWorkers(DEMO_PROFESSIONALS_ENABLED ? [...DEMO_PROFESSIONALS, ...next] : next);
      } catch (error) {
        console.warn('PUNCHX provider online status lookup:', error);
        setWorkers(DEMO_PROFESSIONALS_ENABLED ? [...DEMO_PROFESSIONALS] : []);
      }
    }, error => { console.warn('PUNCHX provider catalogue:', error); setWorkers(DEMO_PROFESSIONALS_ENABLED ? DEMO_PROFESSIONALS : []); });
    return () => unsub();
  }, []);

  const category = selectedCategory || 'All Services';
  const categoryServices = useMemo(() => { const matches = services.filter(s => category.toLowerCase() === 'all services' || category.toLowerCase() === 'all' || s.category.toLowerCase() === category.toLowerCase() || isCategoryMatching(s.category, category)).filter(s => `${s.name} ${s.description} ${s.subcategory}`.toLowerCase().includes(queryText.toLowerCase().trim())); if (DEMO_PROFESSIONALS_ENABLED && matches.length === 0) return DEMO_SERVICES.filter(s => category.toLowerCase() === 'all services' || category.toLowerCase() === 'all' || s.category.toLowerCase() === category.toLowerCase() || isCategoryMatching(s.category, category)).filter(s => `${s.name} ${s.description} ${s.subcategory}`.toLowerCase().includes(queryText.toLowerCase().trim())); return matches; }, [services, category, queryText]);
  useEffect(() => {
    if (!selected) return;
    let cancelled = false;
    const refreshOnline = async () => {
      try {
        const userSnap = await getDocs(query(collection(db, 'users'), where('role', '==', 'worker')));
        const onlineByUid = new Map(userSnap.docs.map(d => [d.id, d.data()?.workerAvailability === true || d.data()?.isOnline === true]));
        if (cancelled) return;
        setWorkers(current => current.map(w => ({ ...w, isOnline: onlineByUid.get((w as any).uid || w.id) === true })));
      } catch (error) {
        console.warn('PUNCHX worker availability refresh:', error);
      }
    };
    void refreshOnline();
    const timer = window.setInterval(refreshOnline, 15000);
    return () => { cancelled = true; window.clearInterval(timer); };
  }, [selected, bookingTiming]);

  const matchingWorkers = useMemo(() => !selected ? [] : workers.filter(w => { if ((!(isCategoryMatching(w.categories || w.category, selected.category) || w.category.toLowerCase() === selected.category.toLowerCase())) || w.available === false) return false; if (bookingTiming === 'instant' && w.isOnline !== true) return false; if (customerGeo && w.location) return calculateDistanceKm(customerGeo.lat, customerGeo.lng, w.location.lat, w.location.lng) <= 15; const area = String(customerGeo?.area || customerGeo?.city || '').toLowerCase(); const workerArea = String(w.area || w.sector || w.address || '').toLowerCase(); return Boolean(area && workerArea && (workerArea.includes(area) || area.includes(workerArea))); }).sort((a,b) => b.rating-a.rating), [workers, selected, bookingTiming, customerGeo]);
  const personalSelectionFeeRate = dispatchMode === 'PERSONAL_SELECT' && completedWithSelectedWorker >= PUNCHX_COMMERCE.personalSelection.freeCompletedBookings ? PUNCHX_COMMERCE.personalSelection.feeRateAfterFreeBookings : 0;
  const personalSelectionFee = Math.round(Number(selected?.price || 0) * personalSelectionFeeRate * 100) / 100;

  useEffect(() => { let cancelled = false; const load = async () => { if (!selectedWorker || !auth.currentUser?.uid) { setCompletedWithSelectedWorker(0); return; } setCountLoading(true); try { const q = query(collection(db,'orders'), where('customerId','==',auth.currentUser.uid), where('workerId','==',selectedWorker.id)); const snap = await getDocs(q); const n = snap.docs.filter(d => ['done','completed'].includes(String(d.data().status || '').toLowerCase())).length; if (!cancelled) setCompletedWithSelectedWorker(n); } catch(e) { console.warn('PUNCHX personal history:', e); if (!cancelled) setCompletedWithSelectedWorker(0); } finally { if (!cancelled) setCountLoading(false); } }; load(); return () => { cancelled = true; }; }, [selectedWorker]);
  const chooseWorker = (w: Worker) => { setDispatchMode('PERSONAL_SELECT'); setSelectedWorker(w); onSelectWorker(w); };

  const next = () => { if (step === 'services' && selected) setStep('details'); else if (step === 'details') setStep('location'); else if (step === 'location') { if (!address.trim()) { showNotification('Please enter the service address.'); return; } setCitizenAddress?.(address.trim()); setStep('datetime'); } else if (step === 'datetime') { if (!date || !time) { showNotification('Please choose a date and time.'); return; } setStep('summary'); } else if (step === 'summary' && selected) { try { localStorage.setItem('punchx_pending_booking', JSON.stringify({ bookingTiming, serviceId:selected.id, serviceName:selected.name, category:selected.category, description:selected.description, price:selected.price ?? null, address:address.trim(), date, time, workerId:dispatchMode === 'PERSONAL_SELECT' ? selectedWorker?.id || null : null, workerName:dispatchMode === 'PERSONAL_SELECT' ? selectedWorker?.name || null : null, workerIsDemo:Boolean(dispatchMode === 'PERSONAL_SELECT' && selectedWorker?.id?.startsWith('demo-')), serviceIsDemo:Boolean(selected.demo), dispatchMode, isPersonalSelection:dispatchMode === 'PERSONAL_SELECT', priorCompletedBookingsWithWorker:completedWithSelectedWorker, personalSelectionFeeRate, personalSelectionFee, createdAt:new Date().toISOString() })); } catch(e) { console.warn('Could not persist pending booking:', e); } onSelectCategory?.(selected.category); if (dispatchMode === 'PERSONAL_SELECT' && selectedWorker) onSelectWorker(selectedWorker); onTransition('booking'); } };
  const back = () => { if (step === 'services') onTransition('home'); else if (step === 'details') setStep('services'); else if (step === 'location') setStep('details'); else if (step === 'datetime') setStep('location'); else setStep('datetime'); };
  const titles: Record<typeof step,string> = { services:category, details:'Service details', location:'Service location', datetime:'Date & time', summary:'Booking summary' };

  return <div className="min-h-screen bg-[#f7f8fa] pb-24 text-[#17191d]"><header className="sticky top-0 z-40 border-b border-black/5 bg-white/95 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-3xl items-center gap-3"><button onClick={back} className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f4f5f7]"><ArrowLeft className="h-5 w-5"/></button><div className="min-w-0 flex-1"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8b9098]">PUNCHX booking</div><h1 className="truncate text-lg font-black">{titles[step]}</h1></div><div className="text-[10px] font-bold text-[#858a93]">{['services','details','location','datetime','summary'].indexOf(step)+1}/5</div></div></header>
  <div className="mx-auto max-w-3xl px-4 pt-5 sm:px-6"><div className="mb-5 grid grid-cols-5 gap-1">{['services','details','location','datetime','summary'].map((item,i)=><div key={item} className={`h-1.5 rounded-full ${i <= ['services','details','location','datetime','summary'].indexOf(step) ? 'bg-[#7358d7]':'bg-[#e5e6ea]'}`}/>)}</div>
  {step==='services' && <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-black/5 sm:p-7"><div className="flex items-center gap-2 rounded-2xl bg-[#f6f7f9] px-3 py-2.5"><Search className="h-4 w-4 text-[#858a93]"/><input value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder={`Search ${category} services`} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none"/>{queryText&&<button onClick={()=>setQueryText('')}><X className="h-4 w-4"/></button>}</div>{loading?<p className="mt-5 rounded-2xl bg-[#f6f7f9] p-5 text-sm text-[#777c85]">Loading PUNCHX services…</p>:categoryServices.length?<div className="mt-5 space-y-3">{categoryServices.map(s=><button key={s.id} onClick={()=>{setSelected(s);setSelectedWorker(null);setDispatchMode('AUTO_MATCH')}} className={`flex w-full gap-4 rounded-2xl border p-4 text-left ${selected?.id===s.id?'border-[#7358d7] bg-[#f3f0ff]':'border-black/5 bg-white'}`}><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-[#f1f2f5]"><Wrench className="h-6 w-6 text-[#777c85]"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><div className="font-black">{s.name}</div>{s.demo&&<span className="rounded-full bg-[#7358d7]/10 px-2 py-0.5 text-[9px] font-black text-[#7358d7]">DEMO</span>}</div><div className="mt-1 text-xs text-[#777c85]">{s.subcategory}</div><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#777c85]">{s.description}</p><div className="mt-2 text-sm font-black">₹{Number(s.price||0).toLocaleString('en-IN')}</div></div>{selected?.id===s.id&&<CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-[#7358d7]"/>}</button>)}</div>:<div className="mt-5 rounded-2xl border border-dashed border-black/10 p-7 text-center"><Wrench className="mx-auto h-8 w-8 text-[#9da2aa]"/><p className="mt-3 font-black">No published services found</p><p className="mt-1 text-sm text-[#777c85]">Demo services are enabled only for PunchX QA testing.</p></div>}</section>}
  {step==='details'&&selected&&<section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5 sm:p-8"><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#f0ecff]"><Wrench className="h-6 w-6 text-[#7358d7]"/></div><div><div className="text-xs font-bold uppercase tracking-wider text-[#8b9098]">Selected service</div><h2 className="text-2xl font-black">{selected.name}</h2>{selected.demo&&<div className="mt-1 text-[10px] font-black uppercase tracking-wider text-[#7358d7]">Demo QA service</div>}</div></div><p className="mt-5 text-sm leading-6 text-[#666b74]">{selected.description}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f6f7f9] p-4"><div className="text-xs text-[#8a8f98]">Price</div><div className="mt-1 font-black">₹{Number(selected.price||0).toLocaleString('en-IN')}</div></div><div className="rounded-2xl bg-[#f6f7f9] p-4"><div className="text-xs text-[#8a8f98]">Professionals</div><div className="mt-1 font-black">{matchingWorkers.length||'Demo matching enabled'}</div></div></div>
  <div className="mt-7 rounded-2xl border border-black/5 bg-[#f7f8fa] p-3"><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#7358d7]">Booking type</div><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setBookingTiming('instant')} className={`rounded-xl border p-3 text-left ${bookingTiming==='instant'?'border-[#7358d7] bg-[#f3f0ff]':'border-black/5 bg-white'}`}><div className="text-xs font-black">Instant / SOS</div><div className="mt-1 text-[10px] text-[#777c85]">Only online professionals are shown.</div></button><button onClick={()=>setBookingTiming('later')} className={`rounded-xl border p-3 text-left ${bookingTiming==='later'?'border-[#7358d7] bg-[#f3f0ff]':'border-black/5 bg-white'}`}><div className="text-xs font-black">Book for later</div><div className="mt-1 text-[10px] text-[#777c85]">All registered professionals in the zone are shown.</div></button></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={()=>{setDispatchMode('AUTO_MATCH');setSelectedWorker(null)}} className={`rounded-2xl border p-4 text-left ${dispatchMode==='AUTO_MATCH'?'border-[#7358d7] bg-[#f3f0ff]':'border-black/5 bg-white'}`}><div className="flex items-center gap-2"><UsersRound className="h-5 w-5 text-[#7358d7]"/><span className="font-black">PunchX Auto-Match</span></div><p className="mt-2 text-xs leading-5 text-[#777c85]">PunchX finds an eligible available professional. <strong>No personal-selection fee.</strong></p></button><button onClick={()=>setDispatchMode('PERSONAL_SELECT')} className={`rounded-2xl border p-4 text-left ${dispatchMode==='PERSONAL_SELECT'?'border-[#7358d7] bg-[#f3f0ff]':'border-black/5 bg-white'}`}><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-[#7358d7]"/><span className="font-black">Choose a professional</span></div><p className="mt-2 text-xs leading-5 text-[#777c85]">Choose someone specific. First {PUNCHX_COMMERCE.personalSelection.freeCompletedBookings} completed bookings with that professional are free.</p></button></div>
  {dispatchMode==='PERSONAL_SELECT'&&<div className="mt-5 rounded-2xl border border-dashed border-[#7358d7]/30 bg-[#faf9ff] p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Available professionals</h3><p className="mt-1 text-xs text-[#777c85]">Instant shows online professionals; later bookings include registered professionals in the service zone.</p></div><span className="rounded-full bg-[#7358d7]/10 px-2.5 py-1 text-[10px] font-black text-[#7358d7]">{DEMO_PROFESSIONALS_ENABLED?'DEMO + REAL':'REAL'}</span></div><div className="mt-3 space-y-2">{matchingWorkers.slice(0,10).map(w=><button key={w.id} onClick={()=>chooseWorker(w)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${selectedWorker?.id===w.id?'border-[#7358d7] bg-[#f0ecff]':'border-black/5 bg-white'}`}><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#eeeafc]"><UserRound className="h-5 w-5 text-[#7358d7]"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="truncate text-sm font-black">{w.name}</span><span className="rounded-full bg-[#f1effa] px-2 py-0.5 text-[9px] font-black text-[#7358d7]">{w.proBadge}</span>{w.id.startsWith('demo-')&&<span className="rounded-full bg-[#fff2c7] px-2 py-0.5 text-[9px] font-black text-[#8a6b16]">DEMO</span>}</div><div className="mt-1 text-xs text-[#777c85]">⭐ {w.rating.toFixed(1)} · {w.reviewsCount} reviews · {w.distanceKm??'—'} km</div><div className="mt-1 text-xs font-bold text-[#555a63]">Visit from ₹{w.visitingFee??w.price}</div><div className="mt-1 text-[10px] text-[#777c85]">{w.isOnline?'Online now':'Registered for later'} · {w.onTimeRate?`${w.onTimeRate} on-time`:`${w.completedJobs??0} jobs`} · {w.identityVerified?'ID verified':'Verification pending'}</div></div>{selectedWorker?.id===w.id&&<CheckCircle2 className="h-5 w-5 shrink-0 text-[#7358d7]"/>}</button>)}{matchingWorkers.length===0&&<p className="rounded-xl bg-white p-4 text-xs text-[#777c85]">No professional is currently matched to this service.</p>}</div></div>}
  {dispatchMode==='PERSONAL_SELECT'&&selectedWorker&&<div className="mt-4 rounded-2xl bg-[#f6f7f9] p-4 text-xs"><div className="font-black">{selectedWorker.name} selected</div><div className="mt-1 text-[#666b74]">{countLoading?'Checking your completed bookings…':completedWithSelectedWorker<PUNCHX_COMMERCE.personalSelection.freeCompletedBookings?`${completedWithSelectedWorker}/${PUNCHX_COMMERCE.personalSelection.freeCompletedBookings} free completed bookings used.`:`Free selection limit reached. A ${Math.round(PUNCHX_COMMERCE.personalSelection.feeRateAfterFreeBookings*100)}% fee applies to this service.`}</div>{personalSelectionFee>0&&<div className="mt-2 font-black text-[#7358d7]">Current preference fee: {formatINR(personalSelectionFee)}</div>}</div>}
  <div className="mt-5 rounded-2xl bg-[#f7f8fa] p-4 text-xs leading-5 text-[#6f747d]"><strong>Service Protection:</strong> PunchX records the booking, professional choice, approved additional work, completion confirmation, invoice and warranty information.</div></section>}
  {step==='location'&&<section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5 sm:p-8"><div className="flex items-center gap-3"><MapPin className="h-6 w-6 text-[#7358d7]"/><div><h2 className="text-xl font-black">Where should we come?</h2><p className="text-sm text-[#777c85]">Use the service address for this booking.</p></div></div><textarea value={address} onChange={e=>setAddress(e.target.value)} placeholder="Enter service address" className="mt-6 min-h-32 w-full resize-none rounded-2xl bg-[#f6f7f9] p-4 text-sm font-semibold outline-none"/><p className="mt-3 text-xs text-[#858a93]">Location permission should only be requested when the active service needs it.</p></section>}
  {step==='datetime'&&<section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5 sm:p-8"><div className="flex items-center gap-3"><CalendarDays className="h-6 w-6 text-[#7358d7]"/><div><h2 className="text-xl font-black">When should we come?</h2><p className="text-sm text-[#777c85]">Choose your preferred date and time. Confirmed availability must come from the backend.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="rounded-2xl bg-[#f6f7f9] p-4"><span className="text-xs font-bold text-[#8a8f98]">Date</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 w-full bg-transparent text-sm font-bold outline-none"/></label><label className="rounded-2xl bg-[#f6f7f9] p-4"><span className="text-xs font-bold text-[#8a8f98]">Time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="mt-2 w-full bg-transparent text-sm font-bold outline-none"/></label></div></section>}
  {step==='summary'&&selected&&<section className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-black/5 sm:p-8"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#7358d7]"/><span className="text-xs font-bold uppercase tracking-wider text-[#7358d7]">Review before confirming</span></div><div className="mt-5 space-y-4 text-sm"><div className="flex justify-between gap-4"><span className="text-[#777c85]">Service</span><span className="text-right font-black">{selected.name}</span></div><div className="flex justify-between gap-4"><span className="text-[#777c85]">Dispatch</span><span className="text-right font-black">{dispatchMode==='PERSONAL_SELECT'?selectedWorker?.name||'Choose a professional':'PunchX Auto-Match'}</span></div><div className="flex justify-between gap-4"><span className="text-[#777c85]">Address</span><span className="max-w-[60%] text-right font-bold">{address}</span></div><div className="flex justify-between gap-4"><span className="text-[#777c85]">Date</span><span className="font-bold">{date}</span></div><div className="flex justify-between gap-4"><span className="text-[#777c85]">Time</span><span className="font-bold">{time}</span></div><div className="flex justify-between gap-4 border-t border-black/5 pt-4"><span className="font-black">Service value</span><span className="font-black">{formatINR(Number(selected.price||0))}</span></div>{dispatchMode==='PERSONAL_SELECT'&&<div className="flex justify-between gap-4"><span className="text-[#777c85]">Specific professional fee</span><span className="font-bold">{formatINR(personalSelectionFee)}</span></div>}<div className="flex justify-between gap-4"><span className="text-[#777c85]">PunchX platform/protection fee</span><span className="font-bold">{formatINR(PUNCHX_COMMERCE.customerPlatformFee)}</span></div><div className="flex justify-between gap-4 border-t border-black/5 pt-4"><span className="font-black">Customer total before checkout</span><span className="font-black">{formatINR(Number(selected.price||0)+PUNCHX_COMMERCE.customerPlatformFee+personalSelectionFee)}</span></div></div><p className="mt-5 rounded-2xl bg-[#f6f7f9] p-4 text-xs leading-5 text-[#6f747d]">Professional commission is deducted from professional payout and is not added again to your bill. Auto-Match/random selection never charges the personal-professional selection fee.</p>{selected.demo&&<p className="mt-3 rounded-2xl bg-[#fff7df] p-4 text-[10px] font-black uppercase tracking-wider text-[#8a6b16]">QA demo booking — not a real professional or live service.</p>}</section>}
  </div><div className="fixed bottom-0 left-0 right-0 z-50 border-t border-black/5 bg-white/95 p-3 backdrop-blur-xl"><div className="mx-auto flex max-w-3xl items-center gap-3"><div className="hidden min-w-0 flex-1 sm:block"><div className="text-xs font-black">{selected?.name||'Select a service'}</div><div className="truncate text-[10px] text-[#858a93]">{dispatchMode==='PERSONAL_SELECT'&&selectedWorker?`Professional: ${selectedWorker.name}`:'PunchX Auto-Match'}</div></div><button onClick={next} disabled={(step==='services'&&!selected)||(step==='details'&&dispatchMode==='PERSONAL_SELECT'&&!selectedWorker)} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#7358d7] px-5 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{step==='summary'?'Continue to checkout':'Continue'}<ArrowRight className="h-4 w-4"/></button></div></div></div>;
}
